%import common.WS
%import common.INT
%ignore WS

// ----------------------
// TERMINAL DEFINITIONS
// ----------------------

MONTHNAME: /(?<![a-z])(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|dec)(?![a-z])/
WEEKDAY: /(?<![a-z])(monday|mon|tuesday|tues|tue|tu|wednesday|wed|thursday|thurs|thur|thu|friday|fri|saturday|sat|sunday|sun)(?![a-z])/
MERIDIEM: /(?<![a-z])([ap](\.?m\.?)?)(?![a-z])/
DATENAME: /(?<![a-z])(today|tomorrow|tmw|yesterday)(?![a-z])/
TIMENAME: /(?<![a-z])(noon|midday|midnight|morning|afternoon|evening|night)(?![a-z])/
DATETIMENAME: /(?<![a-z])(tonight)(?![a-z])/
MONTHNAME_DATE.2: /(?<![a-z])(january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|dec)(?![a-z])\s+\d{1,4}(?:st|nd|rd|th)?(?:\s*,?\s*\d{2,4})?/
DAY_ORDINAL.2: /\d{1,2}(?:st|nd|rd|th)/
DURATION_UNIT: /(?<![a-z])(seconds|second|secs|sec|minutes|mins|min|hours|hour|hrs|hr|h|days|day|weeks|week|wks|wk|months|month|mos|years|year)(?![a-z])/
DURATION_UNIT_LETTER: /(?<=\d)(s|m|h|d|w|mo|y)(?![a-z])/
DURATION_FUTURE: /(?<![a-z])in(?![a-z])/
DURATION_PAST: /(?<![a-z])ago(?![a-z])/
DURATION_NUMBER: /(?<![a-z])(an|a|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)(?![a-z])/
DAY_SUFFIX: /(?<![a-z])(th|rd|st|nd)(?![a-z])/
FLOAT_NUMBER: /((\d+\.\d*|\.\d+)(e[-+]?\d+)?|\d+(e[-+]?\d+))/
NUMERIC_DATE.2: /\d{1,4}\/\d{1,4}(?:\/\d{1,4})?|\d{1,4}\-\d{1,4}\-\d{1,4}/
ISO_DATETIME.3: /\d{4}-\d{1,2}-\d{1,2}T\d{1,2}:\d{2}(?::\d{2}(?:\.\d{1,6})?)?/
TIMEZONE: /(?<![a-z])((TIMEZONE_MAPPING))(?![a-z])/
MODIFIER: /(?<![a-z])(next|last|this|upcoming|previous|past)(?![a-z])/
POSITION: /(?<![a-z])(first|second|third|fourth|last)(?![a-z])/

COLON: ":"

// ----------------------
// PARSER RULES
// ----------------------

start: expression

expression: single
          | list
          | range

range: range_item ("to" | "-") range_item

list: list_item (("," | "or")+ list_item)+

single: datetime
      | duration

range_item: single
          | ambiguous

list_item: range
         | single
         | ambiguous

datetime: date ("at" (time | houronly))? timezone?
        | date (time | houronly) timezone?
        | date "T" time timezone?
        | (time | houronly) date timezone?
        | (time | houronly) "on" date timezone?
        | date timezone?
        | time timezone?
        | datetimename timezone?
        | iso_datetime timezone?

date: weekday? numeric_date
    | weekday? datename
    | weekday? monthname_date
    | weekday? day_ordinal
    | weekday? day DAY_SUFFIX? (",")? year
    | weekday? day DAY_SUFFIX? monthname (",")? year
    | weekday? day DAY_SUFFIX? monthname
    | modified_month
    | position weekday ("of" | "in") monthname
    | modifier weekday ("of" | "in") monthname
    | modified_weekday
    | weekday

time: hour COLON minute (COLON second ("." millisecond)?)? meridiem?
    | hour ("o'clock")? meridiem
    | timename

duration: (DURATION_FUTURE | "for")? duration_part (("and" | ",")? duration_part)* DURATION_PAST?
duration_part: duration_number (duration_unit | duration_unit_letter)
             | duration_numbername " " duration_unit
duration_number: FLOAT_NUMBER | INT
duration_numbername: DURATION_NUMBER+
duration_unit: DURATION_UNIT
duration_unit_letter: DURATION_UNIT_LETTER

datetimename: DATETIMENAME
iso_datetime: ISO_DATETIME
numeric_date: NUMERIC_DATE
monthname_date: MONTHNAME_DATE
day_ordinal: DAY_ORDINAL
modified_weekday: modifier WEEKDAY
                | modifier modifier WEEKDAY
modified_month: modifier MONTHNAME
              | modifier modifier MONTHNAME
weekday: WEEKDAY
monthname: MONTHNAME
datename: DATENAME
dayoryear: INT
ambiguous: INT

day: /0[1-9]|[12][0-9]|3[01]|[1-9]/
month: /0[1-9]|1[0-2]|[1-9]/
year: /\d{4}|(?<!\d)\d{2}(?!\d)/

timename: TIMENAME
hour: INT
minute: INT
second: INT
millisecond: INT
meridiem: MERIDIEM
houronly: INT
timezone: TIMEZONE
modifier: MODIFIER
position: POSITION
